### ISSUE TITLE
other awrt ibus

### ISSUE THREAD

**Issue by justinbro5891** [j4nf4b3l/MagicClock#10]
Can this be used with a different awrt ibus other than magicawrt? Can you pay for a subscription?

**Comment by t3chguru36** [comment]
I Would like to know the same I purchased a different device that also supports multiple watches but didnt realize there was a magicawrt device and magic clock isnt activating because you need the serial number from a magicawrt unit ive even tried using magiccfg it shows the com port after also having to purchase an alex dcsd cable but when you read the SysCFG it does nothing but crash or throw an error ive tried both on mac and windows even different versions of the programs and nothing is working

**Comment by justinbro5891** [comment]
what i've found is hfz tools and mfc software allow you to use other awrt's but the mfc one is super expensive. hfz isnt near the price.
